### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by kassymov17** [bdach/public-transport#7]
Hello, thanks for your projects. Could you send me your backup? I would like to use the project for educational purposes.

**Comment by bdach** [comment]
Hello,

Unfortunately we cannot provide you with any database dump for this application, and we are not actively maintaining it. However, since the database schema design closely resembles the [Google Transit Feed Specification](https://developers.google.com/transit/gtfs/reference/), it should be relatively easy to develop an importer for data stored in the GTFS format.

If you don't mind me asking, can you elaborate as to what will you be using the project for?
